
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - xchain.xuper.baidu.com
  resources:
  - xuperchains
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - xchain.xuper.baidu.com
  resources:
  - xuperchains/finalizers
  verbs:
  - update
- apiGroups:
  - xchain.xuper.baidu.com
  resources:
  - xuperchains/status
  verbs:
  - get
  - patch
  - update
