# permissions for end users to edit xuperchains.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: xuperchain-editor-role
rules:
- apiGroups:
  - xchain.xuper.baidu.com
  resources:
  - xuperchains
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - xchain.xuper.baidu.com
  resources:
  - xuperchains/status
  verbs:
  - get
