apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: '[]'
    capabilities: Basic Install
  name: xuper-operator.v0.0.0
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - description: XuperChain is the Schema for the xuperchains API
      displayName: Xuper Chain
      kind: XuperChain
      name: xuperchains.xchain.xuper.baidu.com
      version: v1alpha1
  description: xuperchain operator
  displayName: xuper-operator
  icon:
  - base64data: ""
    mediatype: ""
  install:
    spec:
      deployments: null
    strategy: ""
  installModes:
  - supported: false
    type: OwnNamespace
  - supported: false
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - xuper
  - xuperchain
  links:
  - name: Xuper Operator
    url: https://xuper-operator.domain
  maturity: alpha
  provider:
    name: xuperchain
  version: 0.0.0
